common/urls.py
from django.urls import path
from . import views

app_name='common'

urlpatterns=[
    path('',views.home,name='home'),
    path('master',views.master,name='master'),
    path('seller_sign',views.seller_sign,name='seller_sign'),
    path('seller_log',views.seller_log,name='seller_log'),
    path('customer_sign',views.customer_sign,name='customer_sign'),
    path('customer_log',views.customer_log,name='customer_log'),



    
    
    
]

customer/urls.py
from django.urls import path
from . import views

app_name='customer'

urlpatterns=[
    path('master',views.master,name='master'),
    path('home',views.home,name='home'),


]

ecom1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
# from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('common.urls')),
    path('seller/',include('seller.urls')),
    path('customer/',include('customer.urls')),


]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

seller/urls.py
from django.urls import path
from . import views

app_name='seller'

urlpatterns=[
    path('home',views.home,name='home'),
    path('addproduct',views.addproduct,name='add_product'),
    path('master',views.master,name='master'),
]

common/models.py
from django.db import models

# Create your models here.


class Seller(models.Model):
    name=models.CharField(max_length=30)
    address=models.CharField(max_length=30)
    email=models.CharField(max_length=30)
    gender=models.CharField(max_length=30)
    phno=models.BigIntegerField(default=1)
    photo=models.ImageField(upload_to='seller/',default='')
    company_name=models.CharField(max_length=30)
    ac_holder_name=models.CharField(max_length=30,default='')
    ac_no=models.CharField(max_length=30,default='')
    ifsc=models.CharField(max_length=30,default='')
    password=models.CharField(max_length=30,default='')
    

    class Meta:
        db_table = 'seller_tb'


class Customer(models.Model):
    name=models.CharField(max_length=30)
    address=models.CharField(max_length=30)
    email=models.CharField(max_length=30)
    gender=models.CharField(max_length=30)
    phno=models.BigIntegerField(default=1)
    photo=models.ImageField(upload_to='seller/',default='')
    company_name=models.CharField(max_length=30)
    ac_holder_name=models.CharField(max_length=30,default='')
    ac_no=models.CharField(max_length=30,default='')
    ifsc=models.CharField(max_length=30,default='')
    password=models.CharField(max_length=30,default='')
    

    class Meta:
        db_table = 'customer_tb'


        

customer/models.py
from django.db import models

# Create your models here.

seller/models.py
from django.db import models

# Create your models here.

common/views.py
from django.shortcuts import render,redirect

from common.models import Seller
from common.models import Customer

# Create your views here.

def home(request):
    return render(request,'common/home.html')

def master(request):
    return render(request,'common/master.html')

def seller_sign(request):
    
    msg=''
    if request.method == 'POST' :

        
        seller_name=request.POST['name']
        seller_add=request.POST['address']
        seller_mail=request.POST['email']
        seller_gender=request.POST['gender']
        seller_ph=request.POST['phone']
        seller_photo=request.FILES['photo']
        seller_company=request.POST['company']
        seller_acholder=request.POST['accountHolder']
        seller_acno=request.POST['accountno']
        seller_ifsc=request.POST['ifsc']
        seller_pw=request.POST['password']

        seller_exist=Seller.objects.filter(email=seller_mail).exists()

        if not seller_exist:
        
            seller=Seller(name=seller_name,
                              address=seller_add,
                              email=seller_mail,
                              gender=seller_gender,
                              phno=seller_ph,
                              photo= seller_photo,
                              company_name=seller_company,
                              ac_holder_name=seller_acholder,
                              ac_no=seller_acno,
                              ifsc=seller_ifsc,
                              password=seller_pw
                              )
            seller.save()
            msg='sign up success'

        else:
            msg='seller already exists'

    return render(request,'common/seller_sign.html',{'message':msg})

def seller_log(request):
    return render(request,'common/seller_log.html')

def customer_sign(request):

    msg=''
    if request.method == 'POST' :

        
        customer_name=request.POST['name']
        customer_add=request.POST['address']
        customer_mail=request.POST['email']
        customer_gender=request.POST['gender']
        customer_ph=request.POST['phone']
        customer_photo=request.FILES['photo']
        customer_company=request.POST['company']
        customer_acholder=request.POST['accountHolder']
        customer_acno=request.POST['accountno']
        customer_ifsc=request.POST['ifsc']
        customer_pw=request.POST['password']

        customer_exist=Customer.objects.filter(email=customer_mail).exists()

        if not customer_exist:
        
            customer=Customer(name=customer_name,
                              address=customer_add,
                              email=customer_mail,
                              gender=customer_gender,
                              phno=customer_ph,
                              photo=customer_photo,
                              company_name=customer_company,
                              ac_holder_name=customer_acholder,
                              ac_no=customer_acno,
                              ifsc=customer_ifsc,
                              password=customer_pw
                              )
            customer.save()
            msg='sign up success'

        else:
            msg='seller already exists'

    

    return render(request,'common/customer_sign.html',{'message':msg})

def customer_log(request):
    return render(request,'common/customer_log.html')

customer/views.py
from django.shortcuts import render

# Create your views here.
def master(request):
     return render(request,'customer/master.html')

def home(request):
     return render(request,'customer/home.html')

seller/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request,'seller/home.html')

def addproduct(request):
    return render(request,'seller/addproduct.html')

def master(request):
    return render(request,'seller/master.html')

common/templates/common/customer_log.html
<html>
<head>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">

</head>
<body>
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h4>Login</h4>
                    </div>
                    <div class="card-body">
                        <form>
                            <div class="form-group">
                                <label for="email">User name</label>
                                <input type="email" class="form-control" id="email" placeholder="Enter your username">
                            </div>
                            <div class="form-group">
                                <label for="password">Password</label>
                                <input type="password" class="form-control" id="password"
                                    placeholder="Enter your password">
                            </div>
                            <button type="submit" class="btn btn-primary">Login</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
        
    </body>
    </html>

common/templates/common/customer_sign.html
{% extends 'common/master.html'%}
{% load static %}

{% block header %}
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <style>
      label {
    color: aliceblue;
  }
  h1,span{
    color: aliceblue;
  }
  </style>
{% endblock %}

  
{% block content %}
    

  <div class="container">
   
    <h1>Signup Form</h1>
    
    <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <span> {{ message }}</span> 
      <div class="form-group">
        <label for="name">Name:</label>
        <input type="text" class="form-control" id="name" name="name" required>
      </div>

      <div class="form-group">
        <label for="address">Address:</label>
        <input type="text" class="form-control" id="address" name="address" required>
      </div>

      <div class="form-group">
        <label for="email">Email Address:</label>
        <input type="email" class="form-control" id="email" name="email" required>
      </div>

      <div class="form-group">
        <label for="gender">Gender:</label>
        <select class="form-control" id="gender" name="gender" required>
          <option value="male">Male</option>
          <option value="female">Female</option>
          <option value="other">Other</option>
        </select>
      </div>

      <div class="form-group">
        <label for="phone">Phone Number:</label>
        <input type="tel" class="form-control" id="phone" name="phone" pattern="[0-9]{10}" required>
      </div>

      <div class="form-group">
        <label for="photo">Photo Upload:</label>
        <input type="file" class="form-control-file" id="photo" name="photo" accept="image/*" required>
      </div>

      <div class="form-group">
        <label for="company">Company Name:</label>
        <input type="text" class="form-control" id="company" name="company" required>
      </div>

      <div class="form-group">
        <label for="accountHolder">Account Holder Name:</label>
        <input type="text" class="form-control" id="accountHolder" name="accountHolder" required>
      </div>
      
      <div class="form-group">
        <label for="accountHolder">AccounT No:</label>
        <input type="text" class="form-control" id="accountHolder" name="accountno" required>
      </div>
     
      <div class="form-group">
        <label for="accountHolder">IFSC Code:</label>
        <input type="text" class="form-control" id="accountHolder" name="ifsc" required>
      </div>
      <div class="form-group">
        <label for="password">Password:</label>
        <input type="password" class="form-control" id="password" name="password" required>
      </div>

      <button type="submit" class="btn btn-primary">Sign Up</button>
    </form>
  </div>

{% endblock %}






  
 

common/templates/common/home.html
{% extends "common/master.html "%}
{% load static %}

{% block header %}
<style>
    body {
        background-color: #eee
    }

    .carousel-inner img {
        width: 100%
    }

    .carousel-item img {
        width: 320px;
        height: 240px !important
    }

    #myCarousel .carousel-indicators {
        position: static;
        margin-top: 0px
    }

    #myCarousel .carousel-indicators>li {
        width: 100px
    }

    #myCarousel .carousel-indicators li img {
        display: block;
        opacity: 0.5
    }

    #myCarousel .carousel-indicators li.active img {
        opacity: 1
    }

    #myCarousel .carousel-indicators li:hover img {
        opacity: 0.75
    }
</style>

{% endblock %}

{% block content %}

<div class="container">
    <div class="row d-flex justify-content-center mt-5">
        <div class="col-md-6">
            <div id="myCarousel" class="carousel slide" data-ride="carousel" align="center">
                <div class="carousel-inner">
                    <div class="carousel-item active"> <img src="https://i.imgur.com/bV1xmG5.jpg" class="rounded">
                    </div>
                    <div class="carousel-item"> <img src="https://i.imgur.com/vgMi4nw.jpg" class="rounded"> </div>
                    <div class="carousel-item"> <img src="https://i.imgur.com/hRlGe10.jpg" class="rounded"> </div>
                </div>
                <ol class="carousel-indicators list-inline">
                    <li class="list-inline-item active"> <a id="carousel-selector-0" class="selected" data-slide-to="0"
                            data-target="#myCarousel"> <img src="https://i.imgur.com/bV1xmG5.jpg"
                                class="img-fluid rounded"> </a> </li>
                    <li class="list-inline-item"> <a id="carousel-selector-1" data-slide-to="1"
                            data-target="#myCarousel"> <img src="https://i.imgur.com/vgMi4nw.jpg"
                                class="img-fluid rounded"> </a> </li>
                    <li class="list-inline-item"> <a id="carousel-selector-2" data-slide-to="2"
                            data-target="#myCarousel"> <img src="https://i.imgur.com/hRlGe10.jpg"
                                class="img-fluid rounded"> </a> </li>
                </ol>
            </div>
        </div>
    </div>
</div>



{% endblock %}

common/templates/common/master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js">
     
    <link rel="stylesheet" href="{% static 'css/master.css' %}">
    {% block header %} 
    
    {% endblock %}
</head>
<body>
  
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid div1" >
          <a class="navbar-brand" href="#">SHOPPEE</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Offers</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Login/Sign In
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Admin</a></li>
                  <li><a class="dropdown-item" href="{% url 'common:seller_sign' %}">Seller</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url 'common:customer_sign' %}">Customer</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled"></a>
              </li>
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>


{% block content %}

{% endblock %}



  




<footer class="bg-white">
  <div class="container py-5">
    <div class="row py-3">

      <div class="col-lg-2 col-md-6 mb-4 mb-lg-0">
        <h6 class="text-uppercase font-weight-bold mb-4">About</h6>
        <ul class="list-unstyled mb-0">
          <li class="mb-2"><a href="#" class="text-muted">Contact Us</a></li>
          <li class="mb-2"><a href="#" class="text-muted">About Us</a></li>
          <li class="mb-2"><a href="#" class="text-muted">Stories</a></li>
          <li class="mb-2"><a href="#" class="text-muted">Press</a></li>
        </ul>
      </div>

      <div class="col-lg-2 col-md-6 mb-4 mb-lg-0">
        <h6 class="text-uppercase font-weight-bold mb-4">Help</h6>
        <ul class="list-unstyled mb-0">
          <li class="mb-2"><a href="#" class="text-muted">Payments</a></li>
          <li class="mb-2"><a href="#" class="text-muted">Shipping</a></li>
          <li class="mb-2"><a href="#" class="text-muted">Cancellation</a></li>
          <li class="mb-2"><a href="#" class="text-muted">Returns</a></li>
        </ul>
      </div>
      
      <div class="col-lg-2 col-md-6 mb-4 mb-lg-0">
        <h6 class="text-uppercase font-weight-bold mb-4">Policy</h6>
        <ul class="list-unstyled mb-0">
          <li class="mb-2"><a href="#" class="text-muted">Return Policy</a></li>
          <li class="mb-2"><a href="#" class="text-muted">Terms Of Use</a></li>
          <li class="mb-2"><a href="#" class="text-muted">Security</a></li>
          <li class="mb-2"><a href="#" class="text-muted">Privacy</a></li>
        </ul>
      </div>
      <div class="col-lg-2 col-md-6 mb-4 mb-lg-0">
        <h6 class="text-uppercase font-weight-bold mb-4">Company</h6>
        <ul class="list-unstyled mb-0">
          <li class="mb-2"><a href="#" class="text-muted">Login</a></li>
          <li class="mb-2"><a href="#" class="text-muted">Register</a></li>
          <li class="mb-2"><a href="#" class="text-muted">Sitemap</a></li>
          <li class="mb-2"><a href="#" class="text-muted">Our Products</a></li>
        </ul>
      </div>
      <div class="col-lg-4 col-md-6 mb-lg-0">
        <h6 class="text-uppercase font-weight-bold mb-4">Registered Office Address</h6>
        <p class="text-muted mb-4">Here , write the complete address of the Registered office address along with telephone number.</p>
        <ul class="list-inline mt-4">
          <li class="list-inline-item"><a href="#" target="_blank" title="twitter"><i class="fab  fa-2x fa-twitter"></i></a></li>
          <li class="list-inline-item"><a href="#" target="_blank" title="facebook"><i class="fab fa-2x fa-facebook-f"></i></a></li>
          <li class="list-inline-item"><a href="#" target="_blank" title="instagram"><i class="fab fa-2x fa-instagram"></i></a></li>
          <li class="list-inline-item"><a href="#" target="_blank" title="pinterest"><i class="fab fa-2x fa-youtube"></i></a></li>
          <li class="list-inline-item"><a href="#" target="_blank" title="vimeo"><i class="fab fa-2x fa-google"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
  <hr class="p-0 m-0 b-0">

 
  <!-- <div class="bg-light py-2">
    <div class="container text-center">
      <p class="text-muted mb-0 py-2">&copy; 2019 BBBootstrap All risghts reserved.</p>
      
      </div>
    </div> -->
  
</footer>

</body>
</html>

common/templates/common/seller_log.html
<!-- {% extends 'common/master.html' %} -->
<!-- {% load static %} -->

<!-- {% block header %} -->
<html>
<head>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<!-- {% endblock %} -->
<!-- {% block content %} -->
</head>
<body>
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h4>Login</h4>
                    </div>
                    <div class="card-body">
                        <form>
                            <div class="form-group">
                                <label for="email">User name</label>
                                <input type="email" class="form-control" id="email" placeholder="Enter your username">
                            </div>
                            <div class="form-group">
                                <label for="password">Password</label>
                                <input type="password" class="form-control" id="password"
                                    placeholder="Enter your password">
                            </div>
                            <button type="submit" class="btn btn-primary">Login</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
        
    </body>
    </html>

    <!-- {% endblock %} -->

common/templates/common/seller_sign.html
{% extends 'common/master.html'%}
{% load static %}

{% block header %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<style>
  label {
    color: aliceblue;
  }
  h5{
    color: aliceblue;
  }
</style>
{% endblock %}


{% block content %}


<div class="container">

  <h1>Signup Form</h1>

  <h5>{{ message }}</h5>
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="form-group">
      <label for="name">Name:</label>
      <input type="text" class="form-control" id="name" name="name" required>
    </div>

    <div class="form-group">
      <label for="address">Address:</label>
      <input type="text" class="form-control" id="address" name="address" required>
    </div>

    <div class="form-group">
      <label for="email">Email Address:</label>
      <input type="email" class="form-control" id="email" name="email" required>
    </div>

    <div class="form-group">
      <label for="gender">Gender:</label>
      <select class="form-control" id="gender" name="gender" required>
        <option value="male">Male</option>
        <option value="female">Female</option>
        <option value="other">Other</option>
      </select>
    </div>

    <div class="form-group">
      <label for="phone">Phone Number:</label>
      <input type="tel" class="form-control" id="phone" name="phone" pattern="[0-9]{10}" required>
    </div>

    <div class="form-group">
      <label for="photo">Photo Upload:</label>
      <input type="file" class="form-control-file" id="photo" name="photo" accept="image/*" required>
    </div>

    <div class="form-group">
      <label for="company">Company Name:</label>
      <input type="text" class="form-control" id="company" name="company" required>
    </div>

    <div class="form-group">
      <label for="accountHolder">Account Holder Name:</label>
      <input type="text" class="form-control" id="accountHolder" name="accountHolder" required>
    </div>

    <div class="form-group">
      <label for="accountHolder">AccounT No:</label>
      <input type="text" class="form-control" id="accountHolder" name="accountno" required>
    </div>

    <div class="form-group">
      <label for="accountHolder">IFSC Code:</label>
      <input type="text" class="form-control" id="accountHolder" name="ifsc" required>
    </div>
    <div class="form-group">
      <label for="password">Password:</label>
      <input type="password" class="form-control" id="password" name="password" required>
    </div>

    <button type="submit" class="btn btn-primary">Sign Up</button>
  </form>
</div>

{% endblock %}

customer/templates/customer/home.html
{% extends 'customer/master.html' %}

{% block header %}

{% endblock %}

{% block content %}
<div class="row">

    
    <div class="col-md-3">
        <div class="card" style="width: 18rem;">
            <img src="" class="card-img-top" alt="Denim Jeans" style="width:30%">
            <div class="card-body">
                <h6></h6>
                <p> </p>
                <p></p>
            </div>

            <p class="price"></p>
            <p></p>
            <p><button>Add to Cart</button></p>
        
        </div>

    </div>


{% endblock %}

customer/templates/customer/master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>

    <style>
      nav img{
        border-radius: 40%;
      }
      nav a{
        color: white;
      }
    </style>
    {% block header %}
  
    {% endblock %}
</head>

<body>
    <header>
        <nav class="navbar bg-body-tertiary">
            <div class="container-fluid" style="margin-top: 10px;background-color: palevioletred;">
              <a class="navbar-brand" href="" style="color: white;">
                <img src="{% static 'images/logo.png' %}" alt="" width="40px" height="30px" class="d-inline-block align-text-top">
                <b></b>
              </a>
            </div>
          </nav>

    </header>
    <div class="row">


    <div class="col-2 border-end">
        <ul class="list-unstyled" style="margin-top: 50%;">
            <li class="d-grid"><a href="{% url 'customer:home' %}" class="btn btn-primary">Home</a> </li><br>
            <li class="d-grid"><a href="" class="btn btn-outline-dark">Profile</a> </li><br>
            <li class="d-grid"><a href="" class="btn btn-outline-secondary">Change password</a> </li><br>
            <li class="d-grid"><a href="" class="btn btn-outline-success">Product details</a> </li><br>
            <li class="d-grid"><a href="" class="btn btn-outline-danger">My cart</a> </li><br>
            <li class="d-grid"><a href="" class="btn btn-outline-warning">My orders</a> </li><br>
            <li class="d-grid"><a href="" class="btn btn-outline-danger">logout</a> </li><br><br>
         

        </ul>

    </div>

    <div class="col-10">

    
    {% block content %}

    {% endblock %}


<footer>
    
    <div class="container-fluid" style="margin-top: 200px;color: black; background-color:palevioletred;padding: 2%;text-align: center;">
        <p><b>Copyright © 2023 PHSS, All Rights Reserved </b></p>


    </div>
</footer>

</body>
</html>

seller/templates/seller/home.html
{% extends 'seller/master.html' %}

seller/templates/seller/master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <m{eta charset="UTF-8"}>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>

   
    {% block header %}

    {% endblock %}
</head>
<body>
    <header>
        <nav class="navbar bg-body-tertiary">
            <div class="container-fluid" style="margin-top: 10px;">
              <a class="navbar-brand" href="">
                <img src="{% static 'images/logo.png' %}" alt="" width="40px" height="30px" class="d-inline-block align-text-top">
                
              </a>
            </div>
            <!-- <button>logout</button> -->

          </nav>

    </header>

    

    
    
<div class="row">


    <div class="col-2 border-end">
        <ul class="list-unstyled" style="margin-top: 50%;">
            <li class="d-grid"><a href="{% url 'seller:home' %}" class="btn btn-primary">Home</a> </li><br>
            <li class="d-grid"><a href="{% url 'seller:add_product' %}" class="btn btn-outline-danger">Add product</a> </li><br>
        
            <li class="d-grid"><a href="" class="btn btn-outline-dark">Profile</a> </li><br>
            <li class="d-grid"><a href="" class="btn btn-outline-secondary">Change password</a> </li><br>
            <li class="d-grid"><a href="" class="btn btn-outline-success">Product cataloge</a> </li><br>
            <li class="d-grid"><a href="" class="btn btn-outline-warning">Recent orders</a> </li><br>
            <li class="d-grid"><a href="" class="btn btn-outline-info">Order History</a> </li><br>
            <li class="d-grid"><a href="" class="btn btn-outline-danger">Update Stock</a> </li><br><br>
            <li class="d-grid"><a href="" class="btn btn-outline-danger">logout</a> </li><br><br>
            
            

        </ul>

    </div>

    <div class="col-10">
        {% block content %}

        {% endblock %}
    </div>
</div> 




<footer>
    
    <div class="container-fluid" style="margin-top: 200px;color: black; background-color:gray;padding: 2%;text-align: center;">
        <p>Copyright © 2023 PHSS, All Rights Reserved</p>


    </div>
</footer>

</body>
</html>